---
- hosts: all
  become: no
  vars:
    # devsec.hardening.ssh_hardening
    sftp_enabled: true
    network_ipv6_enable: false
    # devsec.hardening.os_hardening
    os_env_umask: '022'
    sysctl_overwrite:
      # Enable IPv4 traffic forwarding.  This is relevant for docker and other apps.
      net.ipv4.ip_forward: 1
  collections:
    - ansible.posix
    - community.general
    - devsec.hardening
  roles:
    - baseline
    - unattended-upgrades
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
    - cloud-init
    - sysprep
